sudo: false
dist: trusty
matrix:
  include:
    # Elixir back end
    - language: elixir
      elixir: 1.9.2
      otp_release: 22.1.3
      cache:
        directories:
          - _build
          - deps
      env: MIX_ENV=test
      before_install:
        - cd back_end
      script:
        - mix test
    # Elm front end
    - language: elm
      elm: latest-0.19.1
      elm_test: latest-0.19.1
      elm_format: 0.8.2
      node_js: 15.4.0
      before_install:
        - cd front_end
      install:
        - npm install
        - npm install --global elm-verify-examples elm-analyse elm-format
      script:
        - elm-test --verbose
        - elm-verify-examples --run-tests --fail-on-warn
        - elm-analyse
