sudo: false
dist: trusty
matrix:
  include:
    # Elixir back end
    - language: elixir
      elixir: 1.9.0
      otp_release: 22.0.4
      cache:
        directories:
          - _build
          - deps
      env: MIX_ENV=test
      before_install:
        - cd back_end
      script:
        - mix test
    # Elm front end
    - language: elm
      elm: 0.19.0 #-bugfix6
      elm-test: 0.19.0-rev5
      elm-format: 0.8.1
      # NOTE: Cannot currently use Node 12:
      # https://github.com/halfzebra/create-elm-app/issues/356
      node_js: 11.12.0
      before_install:
        - cd front_end
      install:
        - npm install
        - npm install --global elm-verify-examples elm-analyse elm-format
      script:
        - elm-test --verbose
        - elm-verify-examples --fail-on-warn
        - elm-analyse
