sudo: false
dist: trusty
matrix:
  include:
    # Elixir back end
    - language: elixir
      elixir: 1.9.2
      otp_release: 22.1.3
      cache:
        directories:
          - _build
          - deps
      env: MIX_ENV=test
      before_install:
        - cd back_end
      script:
        - mix test
    # Elm front end
    - language: elm
      elm: 0.19.1
      elm-test: 0.19.1
      elm-format: 0.8.2
      # NodeJS 12.6.0 not currently working on Travis at the moment...
      # node_js: 11.12.0
      node_js: 13.0.1
      before_install:
        - cd front_end
      install:
        - npm install
        - npm install --global elm-verify-examples elm-analyse elm-format
      script:
        - elm-test --verbose
        - elm-verify-examples --run-tests --fail-on-warn
        - elm-analyse
