name: Front end CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  build:
    defaults:
      run:
        working-directory: front_end
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Elm
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1

      - name: Install Global Dependencies
        run: >
          npm install -g
          elm-test
          create-elm-app
          elm-verify-examples
          elm-coverage
          elm-analyse

      - name: Install Local Dependencies
        run: |
          npm install
          cp .env.example .env

      - name: Install Test Dependencies
        working-directory: tests
        run: elm-package install

      - name: Run Tests
        run: elm-test

      - name: Run Verified Examples
        run: elm-verify-examples

      - name: Run Elm Coverage
        run: elm-coverage

      - name: Run Elm Analyse
        run: elm-analyse
